<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";

type Piece = { src: string; title: string; type: string; meta: string; story: string; role: string; process: string };
const pieces: Piece[] = [
  { src: "/studio/bench-detail.png", title: "Quiet Joinery", type: "Furniture system", meta: "Oak · leather · detail study", role: "Concept · modeling · visualization", story: "A study in restraint: a continuous timber structure and reduced junctions.", process: "Proportion studies → structural logic → joinery definition → material rendering" },
  { src: "/studio/mortar.png", title: "Domestic Ritual", type: "Object design", meta: "Stone · timber · material contrast", role: "Object concept · CMF · 3D", story: "An everyday tool treated as a tactile ritual of weight, grip and temperature.", process: "Ergonomic study → silhouette refinement → CMF exploration → product image" },
  { src: "/studio/radios.png", title: "Portable Frequency", type: "Product language", meta: "CMF · retro-futurism · series", role: "Form language · series · visualization", story: "A compact radio family rebuilt through contemporary color, softness and repetition.", process: "Reference archive → family DNA → color system → campaign composition" },
  { src: "/studio/bench.png", title: "Linear Rest", type: "Furniture design", meta: "Structure · proportion · restraint", role: "Furniture concept · detailing", story: "A public bench reduced to a few legible gestures with exposed connections.", process: "Use scenario → ergonomic scale → structural rhythm → final visualization" },
  { src: "/studio/lounge-mint.png", title: "Soft Landscape", type: "Seating concept", meta: "Textile · tubular steel · comfort", role: "Concept · textile study · 3D", story: "A lounge chair imagined as a small upholstered landscape over a precise tubular frame.", process: "Gesture sketches → surface modeling → textile detailing → color variants" },
  { src: "/studio/interior-shadow.png", title: "Shadow Room", type: "Spatial direction", meta: "Light · texture · atmosphere", role: "Interior concept · lighting · image", story: "Arches, mineral textures and moving shadows create a cinematic seating area.", process: "Spatial blocking → material palette → lighting studies → atmosphere pass" },
  { src: "/studio/interior-blue.png", title: "Blue Alcove", type: "Interior visualization", meta: "Materiality · composition · mood", role: "Space · styling · visualization", story: "Architectural grammar shifts character through cooler materials and a tighter composition.", process: "Palette variation → scene styling → contrast study → final render" },
  { src: "/studio/chairs.png", title: "Primary Structure", type: "Furniture family", meta: "Modularity · color · assembly", role: "System design · construction · CMF", story: "A chair system assembled from repeated linear parts and flexible braces.", process: "Assembly logic → modular components → stability study → family variants" },
  { src: "/studio/kempu.png", title: "Kempu", type: "Art direction", meta: "Campaign · typography · image", role: "Art direction · typography · layout", story: "Oversized typography becomes architecture around an image with rhythmic intensity.", process: "Artist context → visual references → typographic gesture → final artwork" },
  { src: "/studio/magnolias.png", title: "Magnolias", type: "Visual identity", meta: "Editorial · type system · artwork", role: "Identity · editorial system · artwork", story: "An editorial identity with display typography and an intimate photographic world.", process: "Concept framing → type exploration → image treatment → release system" },
];
const active = ref(0), selected = ref<number | null>(null), origin = ref({ x: 50, y: 50 }), dragStart = ref<number | null>(null), dragOffset = ref(0), dragging = ref(false);
const current = computed(() => pieces[active.value]);
const go = (direction: number) => active.value = (active.value + direction + pieces.length) % pieces.length;
const offset = (index: number) => { const raw = index - active.value; return raw > pieces.length / 2 ? raw - pieces.length : raw < -pieces.length / 2 ? raw + pieces.length : raw; };
const styleFor = (index: number) => { const value = offset(index), depth = Math.abs(value); return { "--gallery-x": `${value * 34}vw`, "--gallery-y": `${depth * 18}px`, "--gallery-z": `${depth * -190}px`, "--gallery-rotate": `${value * -13}deg`, "--gallery-scale": String(Math.max(.72, 1 - depth * .055)), "--gallery-opacity": String(Math.max(.08, 1 - depth * .18)), "--gallery-saturation": String(Math.max(.25, 1 - depth * .16)) }; };
const pick = (index: number, event: MouseEvent) => { if (index !== active.value) { active.value = index; return; } const rect = (event.currentTarget as HTMLElement).getBoundingClientRect(); origin.value = { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 }; selected.value = index; };
const down = (event: PointerEvent) => { if ((event.target as HTMLElement).closest("button")) return; dragStart.value = event.clientX; dragging.value = true; };
const move = (event: PointerEvent) => { if (dragStart.value === null) return; dragOffset.value = Math.max(-280, Math.min(280, event.clientX - dragStart.value)); };
const up = (event: PointerEvent) => { if (dragStart.value !== null && Math.abs(event.clientX - dragStart.value) > 100) go(event.clientX < dragStart.value ? 1 : -1); dragStart.value = null; dragOffset.value = 0; dragging.value = false; };
const close = () => selected.value = null;
const key = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (selected.value !== null && event.key === "ArrowLeft") selected.value = (selected.value - 1 + pieces.length) % pieces.length; if (selected.value !== null && event.key === "ArrowRight") selected.value = (selected.value + 1) % pieces.length; };
onMounted(() => addEventListener("keydown", key)); onBeforeUnmount(() => removeEventListener("keydown", key));
</script>

<template>
  <div class="creative"><div class="creative-head reveal-item"><span>PROFILE / MATERIAL PRACTICE</span><h2>Beyond screens.<br><em>Ideas with mass.</em></h2><p>Industrial design, 3D visualization and visual direction explored through form, material, light and image.</p></div>
    <div :class="['gallery-shell', { 'is-dragging': dragging }]" :style="{ '--drag-x': `${dragOffset}px` }" @pointerdown="down" @pointermove="move" @pointerup="up" @pointercancel="up"><div class="gallery-grid" /><div class="gallery-stage"><button v-for="(piece, index) in pieces" :key="piece.src" :class="['gallery-card', { 'is-current': index === active }]" :style="styleFor(index)" :aria-label="index === active ? `Open story: ${piece.title}` : `Bring ${piece.title} to front`" @click="pick(index, $event)"><span class="gallery-image"><img :src="piece.src" :alt="piece.title" draggable="false"><i /></span><span class="gallery-card-meta"><small>{{ String(index + 1).padStart(2, '0') }} / {{ String(pieces.length).padStart(2, '0') }}</small><strong>{{ piece.title }}</strong><span>{{ piece.type }}<b>VIEW STORY ↗</b></span></span></button></div><div class="gallery-caption"><span>{{ current.type }}</span><strong>{{ current.title }}</strong><small>{{ current.meta }}</small></div><div class="gallery-controls"><button @click.stop="go(-1)" aria-label="Previous work">←</button><div><button v-for="(piece, index) in pieces" :key="piece.title" :class="{ 'is-current': index === active }" :aria-label="`Go to ${piece.title}`" @click.stop="active = index" /></div><button @click.stop="go(1)" aria-label="Next work">→</button></div><span class="gallery-instruction">DRAG THE SPACE · SELECT AN OBJECT</span></div>
    <div v-if="selected !== null" class="gallery-detail is-open" :style="{ '--origin-x': `${origin.x}px`, '--origin-y': `${origin.y}px` }" role="dialog" aria-modal="true" @click.self="close"><article><button class="gallery-detail-close" autofocus @click="close">CLOSE ×</button><div class="gallery-detail-image"><img :src="pieces[selected].src" alt=""><span>{{ String(selected + 1).padStart(2, '0') }}</span></div><div class="gallery-detail-copy"><span>{{ pieces[selected].type }} / MATERIAL ARCHIVE</span><h3>{{ pieces[selected].title }}</h3><p>{{ pieces[selected].story }}</p><dl><div><dt>ROLE</dt><dd>{{ pieces[selected].role }}</dd></div><div><dt>LANGUAGE</dt><dd>{{ pieces[selected].meta }}</dd></div><div><dt>PROCESS</dt><dd>{{ pieces[selected].process }}</dd></div></dl><div class="gallery-detail-nav"><button @click="selected = (selected - 1 + pieces.length) % pieces.length">← PREVIOUS</button><b>{{ String(selected + 1).padStart(2, '0') }} — {{ String(pieces.length).padStart(2, '0') }}</b><button @click="selected = (selected + 1) % pieces.length">NEXT →</button></div></div></article></div>
  </div>
</template>
